### ISSUE TITLE
Readme: Use example font with spaces

### ISSUE THREAD

**Issue by SebastianVomMeer** [sandelius/font-kit-rails#4]
For a flawless start with the Gem you could change the readme example

     *= require font-kit-rails/ubuntu

to something that makes sure how spaces are handled, e.g.

     *= require font-kit-rails/open-sans

Personally, I tried <code>opensans</code> and <code>open_sans</code> first. Just a minor thing, but it could save some minutes for new users.

**Comment by sandelius** [comment]
fixed
