### ISSUE TITLE
SASS Deprecation Warning

### ISSUE THREAD

**Issue by SebastianVomMeer** [sandelius/font-kit-rails#5]
In newer Rails setups I get the following warning:

    DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename [...]/font-kit-rails-1.1.0/app/assets/stylesheets/font-kit-rails/open-sans.css.scss to [...]/font-kit-rails-1.1.0/app/assets/stylesheets/font-kit-rails/open-sans.scss.

From my Gemfile.lock:

    sass (3.4.11)
    sass-rails (5.0.1)

From my application.sass:

    @import font-kit-rails/open-sans

**Comment by sandelius** [comment]
Fixed in https://github.com/sandelius/font-kit-rails/pull/6
